name: docs

on:
  push:
    branches: [ main ]


# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: cilgroup-page
        channels: conda-forge
        environment-file: environment.yaml
        mamba-version: "*"

    - name: Build the book
      run: |
        make book

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
